### ISSUE TITLE
Context and stuff

### ISSUE THREAD

**Issue by tsloughter** [cvik/heja#1]
Hey, I just saw `heja` in the new packages on hex and took a look. I saw you were using Elli and creating a context with a map. So I wanted to mention this issue on elli https://github.com/elli-lib/elli/issues/35 and https://github.com/tsloughter/ctx in hopes eventually a standard erlang context takes hold :).

I'm really open to anything with `ctx`, the main feature I've been still toying with how to get right is deadlines which I need for grpc, https://github.com/tsloughter/grpcbox

**Comment by cvik** [comment]
Hi, sorry for the the late reply (have been gone). Look's like a good idea. I will take a look.
