### ISSUE TITLE
Deps missing form hex package

### ISSUE THREAD

**Issue by tsloughter** [cvik/heja#2]
Somehow the dependencies were not included when publishing the hex package: https://hex.pm/packages/heja

The rebar3 hex plugin will output what dependencies it is publishing with the package before asking to continue, so you can check there before publishing again.

I can't say why this might have happened since usually this occurs when a project was still using git dependencies but I see the config uses hex packages and has them properly locked..

**Comment by cvik** [comment]
Thanks! I noticed this when I tried to use it. Turned out I had an old version of the hex-plugin. Should be fixed in the 0.1.3 version.
