### ISSUE TITLE
Multiple methods for same path causes method_not_allowed for some

### ISSUE THREAD

**Issue by rost** [cvik/heja#8]
When adding multiple methods for the same path, e.g.

```
heja:get(Ref, "/api/v1/users/:id", Fun1).
heja:put(Ref, "/api/v1/users/:id", Fun2).
heja:delete(Ref, "/api/v1/users/:id", Fun3).
```

only one of them work, and the rest returns `method_not_allowed`. I haven't figured out what combinations of them cause exactly which method to fail.

**Comment by cvik** [comment]
Acknowledged.
